// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Eh_NzbTbSdOdtAkAobVnT8Hl2rWD3EY',
    appId: '1:74618658038:web:6475478d68a6417be3a0d7',
    messagingSenderId: '74618658038',
    projectId: 'loginstatgem',
    authDomain: 'loginstatgem.firebaseapp.com',
    storageBucket: 'loginstatgem.firebasestorage.app',
    measurementId: 'G-QY3C6BE6H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI-8t7m4-IEn5KTJ3F7cYFzqsO_aAvFWg',
    appId: '1:74618658038:android:834a58f3f4c5089fe3a0d7',
    messagingSenderId: '74618658038',
    projectId: 'loginstatgem',
    storageBucket: 'loginstatgem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwQ9O7sXIZIzloOucqdPm9NsgvmBCdfaE',
    appId: '1:74618658038:ios:1d38674de01d1ee8e3a0d7',
    messagingSenderId: '74618658038',
    projectId: 'loginstatgem',
    storageBucket: 'loginstatgem.firebasestorage.app',
    iosBundleId: 'com.example.bpsELearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwQ9O7sXIZIzloOucqdPm9NsgvmBCdfaE',
    appId: '1:74618658038:ios:1d38674de01d1ee8e3a0d7',
    messagingSenderId: '74618658038',
    projectId: 'loginstatgem',
    storageBucket: 'loginstatgem.firebasestorage.app',
    iosBundleId: 'com.example.bpsELearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Eh_NzbTbSdOdtAkAobVnT8Hl2rWD3EY',
    appId: '1:74618658038:web:0efecf54e463a0dde3a0d7',
    messagingSenderId: '74618658038',
    projectId: 'loginstatgem',
    authDomain: 'loginstatgem.firebaseapp.com',
    storageBucket: 'loginstatgem.firebasestorage.app',
    measurementId: 'G-D756RYPR7M',
  );
}
